[package]
name = "DataFilter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
railsgun = "1.0.3"
regex = "1.5.6"
serde = "1.0.137"
serde_json = "1.0.81"
